version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: comptaohada
      POSTGRES_USER: comptaohada_user
      POSTGRES_PASSWORD: comptaohada_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comptaohada_user -d comptaohada"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis pour le cache et les tâches asynchrones
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://comptaohada_user:comptaohada_password@db:5432/comptaohada
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend/src:/app
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Next.js (à implémenter)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    # command: npm run dev

volumes:
  postgres_data:
  redis_data:
